version: '3.8'

services:

#  app:
#    container_name: spring-boot-ldap
#    build:
#      dockerfile: Dockerfile
#    expose:
#      - "8080:8080"
#    depends_on:
#      - openldap
#    restart: always

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_DOMAIN: "example.com"
    ports:
      - "389:389"
      - "636:636"
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap
    networks:
      - openldap

networks:
  openldap:
    driver: bridge